### ISSUE TITLE
question: Is it possible to port this to macOS?

### ISSUE THREAD

**Issue by bossanovaorca** [lilydjwg/copy-link-address#2]
thank you for creating this extension, I use it on all of my Windows devices. is it also possible to port this to macOS?

**Comment by lilydjwg** [comment]
There should not be anything specific to the OS. Have you tried it on macOS, and if so, do you see any problems?

**Comment by bossanovaorca** [comment]
when I right click a link and press <kbd>A</kbd> on macOS, "Copy link location" is not selected. I assume this is due to how macOS context menus handle key presses?

**Comment by lilydjwg** [comment]
Maybe access keys just don't work there. I don't know much about macOS.

**Comment by bossanovaorca** [comment]
ok I see, I will close this for now
